steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/reto-tecnico:${SHORT_SHA}", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/reto-tecnico:${SHORT_SHA}"]
    # deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "reto-tecnico",
        "--image",
        "gcr.io/$PROJECT_ID/reto-tecnico:${SHORT_SHA}",
        "--region",
        "us-west1",
        "--allow-unauthenticated",
      ]
    env:
      - "PORT=8080"
images:
  - gcr.io/$PROJECT_ID/reto-tecnico